<?php

namespace center\modules\appointment\models;

use center\modules\Core\interfaces\BaseModelInterface;
use center\modules\Core\models\BaseActiveRecord;
use center\modules\log\models\LogWriter;
use Yii;
use yii\helpers\Json;

/**
 * This is the model class for table "domain_managers".
 *
 * @property integer $id
 * @property string $domain
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 */
class ImportFiles extends BaseActiveRecord implements BaseModelInterface
{
    public $default_field = ['id', 'file', 'status', 'mgr_name','result','created_at', 'updated_at'];


    public function beforeSave($insert)
    {
        if ($insert) {
            $this->created_at = $this->updated_at = time();
            $this->mgr_id = Yii::$app->user->identity->getId();
            $this->mgr_name = $this->getMgrName();
        } else {
            $this->updated_at = time();
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'upload_files';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status', 'created_at', 'updated_at'], 'integer'],
            [['file'], 'file'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'domain' => Yii::t('app', 'domain'),
            'status' => Yii::t('app', 'status'),
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    //搜索字段
    private $_searchField = null;

    public function getSearchField()
    {
        // TODO: Implement getSearchField() method.
        return [
            'id' => 'ID',
            'file' => Yii::t('app', '上传文件'),
            'result' => Yii::t('app', '处理结果'),
            'status' => Yii::t('app', 'status'),
            'created_at' => '创建时间',
            'updated_at' => '最后更新时间',
            'start_time' => '最后更新时间',
            'stop_time' => '最后更新时间',
            'mgr_name' => '操作员',
        ];
    }

    public function getSearchInput()
    {
        // TODO: Implement getSearchInput() method.
        //扩展字段加入搜索
        $exField = [];

        return yii\helpers\ArrayHelper::merge([

            'status' => [
                'label' => Yii::t('app', 'status'),
                'list' => [
                    '' => '请选择',
                    0 => '未处理',
                    1 => '处理成功',
                    2 => '处理中',
                    3 => '处理失败'
                ]
            ],

            'start_time' => [
                'label' => Yii::t('app', 'start opt time'),
                'class' => '  inputDate'
            ],
            'stop_time' => [
                'label' => Yii::t('app', 'end opt time'),
                'class' => '  inputDate'
            ]

        ], $exField);
    }

    public function getAttributesList()
    {
        // TODO: Implement getAttributesList() method.
        //扩展字段加入搜索
        $exField = [];

        return yii\helpers\ArrayHelper::merge([
            'status' => [
                '' => '请选择',
                0 => '未处理',
                1 => '处理成功',
                2 => '处理中',
                3 => '处理失败'
            ],

            'start_time' => [
                'label' => Yii::t('app', 'start opt time'),
                'class' => '  inputDate'
            ],
            'stop_time' => [
                'label' => Yii::t('app', 'end opt time'),
                'class' => '  inputDate'
            ]

        ], $exField);
    }
}
