<?php


namespace center\modules\api\controllers;

use center\modules\appointment\models\SmsHistory;
use common\models\Redis;
use Yii;
use center\controllers\ApiController;

/**
 * phone
 * Class PhoneController
 * @package center\modules\api\controllers
 */
class PhoneController extends ApiController
{
    public $model;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->model = new SmsHistory();
    }

    public function actionSend()
    {
        $params = Yii::$app->request->queryParams;

        if (!isset($params['phone'])) {
            return self::returnJson(406, [
                'code' => 406,
                'msg' => '参数缺失'
            ]);
        }

        if (!$this->checkParams($params)) {
            return self::returnJson(403, [
                'code' => 403,
                'msg' => json_encode($this->model->getErrors(), JSON_UNESCAPED_UNICODE)
            ]);
        }

        if (!$this->checkSign($params, true)) {
            return self::returnJson(408, [
                'code' => 408,
                'message' => '验签不通过'
            ]);
        }
        $model = $this->model;
        $phone = $params['phone'];
        $res = $model->sendPaaSooCode($phone);

        return self::returnJson($res['code'], $res);
    }


    public function actionVerify($phone, $code)
    {


    }

}